import type { Subscription } from './types';

export const SAMPLE_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    amount: 15.99,
    billingCycle: 'monthly',
    nextRenewal: '2026-03-15',
    category: 'Entertainment',
    color: '#E50914',
    active: true,
  },
  {
    id: '2',
    name: 'Spotify',
    amount: 9.99,
    billingCycle: 'monthly',
    nextRenewal: '2026-03-08',
    category: 'Entertainment',
    color: '#1DB954',
    active: true,
  },
  {
    id: '3',
    name: 'GitHub Pro',
    amount: 4.0,
    billingCycle: 'monthly',
    nextRenewal: '2026-03-20',
    category: 'Productivity',
    color: '#24292F',
    active: true,
  },
  {
    id: '4',
    name: 'Notion',
    amount: 16.0,
    billingCycle: 'monthly',
    nextRenewal: '2026-03-25',
    category: 'Productivity',
    color: '#000000',
    active: true,
  },
  {
    id: '5',
    name: 'Adobe Creative Cloud',
    amount: 599.88,
    billingCycle: 'yearly',
    nextRenewal: '2026-11-01',
    category: 'Productivity',
    color: '#FF0000',
    active: true,
  },
  {
    id: '6',
    name: 'iCloud+',
    amount: 2.99,
    billingCycle: 'monthly',
    nextRenewal: '2026-03-10',
    category: 'Cloud Storage',
    color: '#1C7EEA',
    active: true,
  },
  {
    id: '7',
    name: 'New York Times',
    amount: 17.0,
    billingCycle: 'monthly',
    nextRenewal: '2026-04-01',
    category: 'News & Media',
    color: '#000000',
    active: false,
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Entertainment: '#8B5CF6',
  Productivity: '#3B82F6',
  'Health & Fitness': '#10B981',
  Education: '#F59E0B',
  Finance: '#EF4444',
  'News & Media': '#6B7280',
  'Cloud Storage': '#06B6D4',
  Other: '#9CA3AF',
};
